name: startAndRunLocustLoadTestingOnEC2

on:
  workflow_dispatch:

jobs:
  start_ec2_instance:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Start EC2 Instance
        run: aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
      - name: Run Locust Test
        run: aws ssm send-command \
          --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters commands='["locust -f load_test.py --headless -u 2 -t 1m --html load_test_result.html"]' \
      - name: Terminate EC2 Instance
        run: aws ec2 stop-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
